version: "3.7"

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "airline-management-system"
      POSTGRES_PASSWORD: "admin123"
